config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }

  devise_scope :user do
    get "sign_in",  to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end
  root 'staticpage#index'
  # get 'search/:id', to: "search#index"
  resources :posts, only: [:show, :new, :edit, :create, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :categories, only: [:show, :create]
  resources :searchs, only: [:index]
end

app/views/shared/_footer.html.erb
<p id="footer">©2020 6ch Inc.</p>

app/views/shared/_header.html.erb
<div id="header">
  <div class="logo">
    <%= link_to "6CH", root_path %>
  </div>  
  <div class="link">
    <ul id="nav">
      <li>
        <div class="search-tag">
          <%= form_tag(searchs_path,:method => 'get') do %>
            <%= text_field_tag :search, '', placeholder: "検索" %>
            <%= submit_tag 'Search', id: 'search_submit' %>
          <% end %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to "投稿", new_post_path %>
        </li>
        <li>
          <%= link_to 'マイページ', edit_user_registration_path %>
        </li>
        <li>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to 'ログイン', new_user_session_path %>
        </li>
        <li>
          <%= link_to '新規登録', new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if flash[:notice].present? %>
  <div class="toast">
    <div class="notice"><%= notice %></div>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="toast">
    <div class="alert"><%= alert %></div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="box">
    <div class="image">
      <%= image_tag 'キリン.jpg' %>
    </div>
    <div class="coment">
      6chへようこそ！
    </div>
  </div>
  <div class="box category">
    <p>【カテゴリ一覧】</p>
    <ul>
      <% @categories.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
      <% end %>
    </ul>
    </div>
      </div>
    </div>