config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }

  devise_scope :user do
    get "sign_in",  to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end
  root 'staticpage#index'
  # get 'search/:id', to: "search#index"
  resources :posts, only: [:show, :new, :edit, :create, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :categories, only: [:show, :create]
  resources :searchs, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations, dependent: :destroy
  validates :user_id, presence: true
  validates :content, presence: true
  validates :title, presence: true, length: { maximum: 60 }

  def self.search(search)
    if search.blank?
      Post.none
    else
      Post.where(['content LIKE ?', "%#{search}%"])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @comments = @post.comments
    @comment = Comment.new
    @categories = Category.all
  end

  def new
    @post = Post.new
    @category = Category.new
  end

  def edit
    @category = Category.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: "投稿に成功しました"
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path, notice: "投稿を更新しました"
    else
      flash.now[:alert] = "投稿を更新できませんでした"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path, notice: "投稿を削除しました"
    else
      redirect_to root_path, notice: "投稿を削除できませんでした"
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :title, :user_id, category_ids: [])
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/views/posts/_add_comment.html.erb
<button type="button" class="btn_add_list" data-toggle="modal" data-target="#exampleModal-<%= c.id %>">返信</button>
<div class="modal fade" id="exampleModal-<%= c.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog wid" role="document">
    <div class="modal-content">
      <%= form_with(model:[post,comment], local: true) do |f| %>
        <div class="modal-body pd15170">
          <p>レスを投稿する</p>
          <ul class="modal-ul">
            <li>
              <%= f.text_area :body, rows: 9, value: ">>#{n+2}" %>
            </li>
          </ul>
        </div>
        <div class="modal-footer textcenter">
          <%= f.hidden_field :post_id, value: post.id %>
          <%= f.hidden_field :parent_id, value: c.id %>
          <%= f.submit "書き込む", class: "btn circle-btn" %>
          <button type="button" class="btn circle-btn pl-10" data-dismiss="modal">閉じる</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="main">
  <h1>投稿を編集する</h1>
  <div class="add-category">
    <%= form_with(model: @category, local: true) do |f| %>
      <%= f.label :name, '新しいカテゴリ' %>
      <%= f.text_field :name %>
      <%= f.submit "追加", class: "button" %>
    <% end %>
  </div>  
  <div class="add-post">
    <%= form_with(model: @post, local: true) do |f| %>
      <p>[カテゴリ]</p>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
        <%= category.label do %>
          <%= category.check_box %>
          <%= category.text %>
        <% end %>
      <% end %>
      <p>[タイトル]</p>
      <%= f.text_area :title, maxlength: 60, rows: 1, placeholder: "60文字以下" %>
      <p>[本文]</p>
      <%= f.text_area :content, rows: 5 %>
      <div class="submit-block">
        <%= f.submit "更新する", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main">
  <h1>投稿を作成する</h1>
  <div class="add-category">
    <%= form_with(model: @category, local: true) do |f| %>
      <%= f.label :name, '新しいカテゴリ' %>
      <%= f.text_field :name %>
      <%= f.submit "追加", class: "button" %>
    <% end %>
  </div>  
  <div class="add-post">
    <%= form_with(model: @post, local: true) do |f| %>
      <p>[カテゴリ]</p>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
        <%= category.label do %>
          <%= category.check_box %>
          <%= category.text %>
        <% end %>
      <% end %>
      <p>[タイトル]</p>
      <%= f.text_area :title, maxlength: 60, rows: 1, placeholder: "60文字以下" %>
      <p>[本文]</p>
      <%= f.text_area :content, rows: 5 %>
      <div class="submit-block">
        <%= f.submit "投稿する", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="content-wrapper">
  <div class="content-block">
    <div class="title">
      <h3><%= @post.title %>[<%= @post.user.name %>]</h3>
    </div>
    <div class="category">
      <span>★カテゴリ★</span>
      <span class="ml20">
        <% @post.categories.each do |category| %>
          <%= link_to "[#{category.name}]", category_path(category) %>
        <% end %>
      </span>
    </div>
    <div class="sured">
      <div class="name">
        <p>1 <span><%= @post.user.name %></span> <%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
      </div>
      <div class="content">
        <%= @post.content %>
      </div>
      <% if current_user?(@post.user) %>
        <div class="link">
          <%= link_to "編集", edit_post_path(@post) %>
          <%= link_to "削除", post_path(@post), data: { confirm: "Are you sure?" }, method: :delete %>
        </div>
      <% end %>
    </div>
    <% @comments.each_with_index do |c, n| %>
      <div class="sured" id=<%=c.id%>>
        <div class="name">
          <p><%= n+2 %> <span><%= c.user.name %></span> <%= c.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
          <span>
            <% unless c.replies.nil? %>
              <% c.replies.each do |replie| %>
                <%= link_to "↓#{replie.user.name}", post_path(anchor: replie.id ), class: 'post' %>
              <% end %>
            <% end %>
          </span>
          </p>
          <% unless c.parent.nil? %>
            <%= link_to "↑#{c.parent.user.name}", post_path(anchor: c.parent.id ), class: 'post' %>
          <% end %>
        </div>
        <div class="content">
          <%= c.body %>
        </div>
        <div class="link">
          <% if user_signed_in? %>
            <%= render 'add_comment', comment: @comment, post: @post, c: c, n: n %>
          <% end %>
          <% if current_user?(c.user) %>
            <%= link_to "削除", comment_path(c), data: { confirm: "Are you sure?" }, method: :delete %>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if user_signed_in? %>
    <div class="comments-area">
      <h2>コメントする</h2>
      <%= form_with(model:[@post,@comment], local: true) do |f| %>
        <%= f.text_area :body, rows: 4, id: "comment_area" %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <div class="submit-block">
          <%= f.submit "投稿", class: "button", id: "comment_btn" %>
        </div>
      <% end %> 
    </div>
    <% end %>
  </div>
  <%= render 'shared/sidebar' %>
</div>