config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }

  devise_scope :user do
    get "sign_in",  to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end
  root 'staticpage#index'
  # get 'search/:id', to: "search#index"
  resources :posts, only: [:show, :new, :edit, :create, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :categories, only: [:show, :create]
  resources :searchs, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_category_relations, dependent: :destroy
  has_many :posts, through: :post_category_relations, dependent: :destroy
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "カテゴリの作成に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @posts = @category.posts.includes([:user])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/show.html.erb
<div class="content-wrapper">
  <div class="content-block">
    <div class="category-name">
      <h1><%= @category.name %><span>のスレッド一覧</span></h1>
    </div>
    <% unless @posts.blank? %>
    <% @posts.each do |post|%>
      <div class="content">
        <div class="title-block">
          <div class="image">
            <%= image_tag '男性.jpg' %>
          </div>
          <div class="main-title">
            <%= link_to post_path(post) do %>
              <div class="title">
                <p><%= post.title %>[<%= post.user.name %>]</p>
              </div>
            <% end %>
          </div>
        </div>
        <div class="text">
          <p><%= post.content %></p>
        </div>
        <div class="action-menu">
          <div class="like">
          </div>
          <div class="comment">
          </div>
        </div>
      </div>
    <% end %>
    <% else %>
      <div class="content">
        <p>スレッドはありません</p>
      </div>
    <% end %>
  </div>
  <%= render 'shared/sidebar' %>
</div>